/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.insured {
	import com.catlin.cargo.model.core.party.Party;
	import com.catlin.cargo.model.geo.address.Address;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.insured.Insured")]
    public class Insured extends InsuredBase {
    	public function Insured(i:Party = null) {
    		if (i == null) return;
    		this.name = i.name;
			this.address = new Address();
    		this.address.addressLine1 = i.address.addressLine1;
			this.address.addressLine2 = i.address.addressLine2;
			this.address.addressLine3 = i.address.addressLine3;
			this.address.townCity = i.address.townCity;
			this.address.county = i.address.county;
			this.address.country = i.address.country;
			this.address.postcode = i.address.postcode;
			this.address.province = i.address.province;
    	}
    }
}