/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.covertype {

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.covertype.CoverTypeDefaults")]
    public class CoverTypeDefaults extends CoverTypeDefaultsBase {
    }
}