/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.covertype {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.covertype.CoverTypeCode")]
    public class CoverTypeCode extends Enum {

        public static const BUYER_SELLER:CoverTypeCode = new CoverTypeCode("BUYER_SELLER", _);
        public static const DOMESTIC_TRANSITS:CoverTypeCode = new CoverTypeCode("DOMESTIC_TRANSITS", _);
        public static const FREE_ON_BOARD:CoverTypeCode = new CoverTypeCode("FREE_ON_BOARD", _);
        public static const GOODS_IN_TRANSIT:CoverTypeCode = new CoverTypeCode("GOODS_IN_TRANSIT", _);
        public static const IMPORT_EXPORT:CoverTypeCode = new CoverTypeCode("IMPORT_EXPORT", _);
        public static const EXHIBITION:CoverTypeCode = new CoverTypeCode("EXHIBITION", _);
        public static const TOOLS_AND_SAMPLES:CoverTypeCode = new CoverTypeCode("TOOLS_AND_SAMPLES", _);
        public static const STOCK:CoverTypeCode = new CoverTypeCode("STOCK", _);
        public static const STOCK_CATASTROPHE:CoverTypeCode = new CoverTypeCode("STOCK_CATASTROPHE", _);

        function CoverTypeCode(value:String = null, restrictor:* = null) {
            super((value || BUYER_SELLER.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [BUYER_SELLER, DOMESTIC_TRANSITS, FREE_ON_BOARD, GOODS_IN_TRANSIT, IMPORT_EXPORT, EXHIBITION, TOOLS_AND_SAMPLES, STOCK, STOCK_CATASTROPHE];
        }

        public static function valueOf(name:String):CoverTypeCode {
            return CoverTypeCode(BUYER_SELLER.constantOf(name));
        }
    }
}