/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.brokeroffice {
	import com.catlin.cargo.model.core.link.BrokerOfficeLinkEntry;
	
	import mx.collections.ListCollectionView;
	
	import org.granite.persistence.PersistentList;
	

	[Bindable]
	[RemoteClass(alias="com.catlin.cargo.model.core.brokeroffice.BrokerOffice")]
	public class BrokerOffice extends BrokerOfficeBase {

		public var _refreshOfBrokerDocumentsRequired:Boolean  = false;
		
		private static const _importedClasses:Array = [ BrokerOfficeLinkEntry ];
		
		public function BrokerOffice() {
			super();
			premiumLimitAnnual = 0;
			premiumLimitSingle = 0;
			minimumPremiumAnnual = 0;
			minimumPremiumSingle = 0;
			settlementDays = 0;
			defaultCommission = 0;
			discountCap = 0;
			loadingRate = 1;
		}
		
		public function set refreshOfBrokerDocumentsRequired(value:Boolean):void {
			_refreshOfBrokerDocumentsRequired = value; 
		}
		public function get refreshOfBrokerDocumentsRequired():Boolean {
			return _refreshOfBrokerDocumentsRequired;
		}
		
		public override function set usefulLinks(ul:ListCollectionView):void {
			var pl:PersistentList = new PersistentList();
			pl.addAll(ul);
			usefulLinks = pl; 
		}
	}
}