/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.clause {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.clause.ClauseType")]
    public class ClauseType extends Enum {

        public static const STANDARD:ClauseType = new ClauseType("STANDARD", _);
        public static const NON_STANDARD:ClauseType = new ClauseType("NON_STANDARD", _);
        public static const TRIA:ClauseType = new ClauseType("TRIA", _);

        function ClauseType(value:String = null, restrictor:* = null) {
            super((value || STANDARD.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [STANDARD, NON_STANDARD, TRIA];
        }

        public static function valueOf(name:String):ClauseType {
            return ClauseType(STANDARD.constantOf(name));
        }
    }
}