/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.clause {

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.clause.Clause")]
    public class Clause extends ClauseBase {
    	
    	public function Clause() { 
    		active = true;
    	}
    }
}