/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.documents.document {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.documents.document.DocumentDiscriminatorType")]
    public class DocumentDiscriminatorType extends Enum {

        public static const CONSUMER_TYPE:DocumentDiscriminatorType = new DocumentDiscriminatorType("CONSUMER_TYPE", _);
        public static const PROVINCE:DocumentDiscriminatorType = new DocumentDiscriminatorType("PROVINCE", _);

        function DocumentDiscriminatorType(value:String = null, restrictor:* = null) {
            super((value || CONSUMER_TYPE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [CONSUMER_TYPE, PROVINCE];
        }

        public static function valueOf(name:String):DocumentDiscriminatorType {
            return DocumentDiscriminatorType(CONSUMER_TYPE.constantOf(name));
        }
    }
}