/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.documents.document {
	
	
	[Bindable]
	[RemoteClass(alias="com.catlin.cargo.model.documents.document.Document")]
	public class Document extends DocumentBase {

		public static function getDocumentName(document:DocumentType):String {
			
			switch (document) {
				case DocumentType.QUOTE_SCHEDULE:
					return "Quote Schedule";
				case DocumentType.DEBIT_NOTE:
					return "Debit Note";
				case DocumentType.KEY_FACTS:
					return "Key Facts";
				case DocumentType.WORDINGS:
					return "Wording";
				case DocumentType.POLICY_SCHEDULE:
					return "Policy Schedule";
				case DocumentType.STORAGE_QUESTIONNAIRE:
					return "Storage Questionnaire";
				case DocumentType.CLAUSE:
					return "Clause";
				case DocumentType.RATING_SCHEDULE:
					return "Rating Schedule";
				case DocumentType.SCHEDULE:
					return "Schedule";
				case DocumentType.CANCELLATION_NOTE:
					return "Cancellation Endorsement";
				case DocumentType.DEFINITIONS:
					return "Definitions";
				case DocumentType.POLICY_CHANGES:
					return "Policy Changes";
				case DocumentType.POLICY_SUMMARY:
					return "Policy Summary";
                case DocumentType.IPID:
                    return "IPID";
				case DocumentType.NOTICE_TO_POLICYHOLDERS:
					return "Notice To Policyholders";
				default:
					return "Unknown";
			}
		}
	}
}
