/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.documents.document {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.documents.document.Document$StoreNames")]
    public class Document$StoreNames extends Enum {

        public static const TEMPLATE:Document$StoreNames = new Document$StoreNames("TEMPLATE", _);
        public static const REPOSITORY:Document$StoreNames = new Document$StoreNames("REPOSITORY", _);

        function Document$StoreNames(value:String = null, restrictor:* = null) {
            super((value || TEMPLATE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [TEMPLATE, REPOSITORY];
        }

        public static function valueOf(name:String):Document$StoreNames {
            return Document$StoreNames(TEMPLATE.constantOf(name));
        }
    }
}