/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.documents.document {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.documents.document.DocumentType")]
    public class DocumentType extends Enum {

        public static const QUOTE_SCHEDULE:DocumentType = new DocumentType("QUOTE_SCHEDULE", _);
        public static const DEBIT_NOTE:DocumentType = new DocumentType("DEBIT_NOTE", _);
        public static const KEY_FACTS:DocumentType = new DocumentType("KEY_FACTS", _);
        public static const POLICY_SUMMARY:DocumentType = new DocumentType("POLICY_SUMMARY", _);
        public static const IPID:DocumentType = new DocumentType("IPID", _);
        public static const WORDINGS:DocumentType = new DocumentType("WORDINGS", _);
        public static const POLICY_SCHEDULE:DocumentType = new DocumentType("POLICY_SCHEDULE", _);
        public static const STORAGE_QUESTIONNAIRE:DocumentType = new DocumentType("STORAGE_QUESTIONNAIRE", _);
        public static const CLAUSE:DocumentType = new DocumentType("CLAUSE", _);
        public static const RATING_SCHEDULE:DocumentType = new DocumentType("RATING_SCHEDULE", _);
        public static const SCHEDULE:DocumentType = new DocumentType("SCHEDULE", _);
        public static const CANCELLATION_NOTE:DocumentType = new DocumentType("CANCELLATION_NOTE", _);
        public static const DEFINITIONS:DocumentType = new DocumentType("DEFINITIONS", _);
        public static const POLICY_CHANGES:DocumentType = new DocumentType("POLICY_CHANGES", _);
        public static const NOTICE_TO_POLICYHOLDERS:DocumentType = new DocumentType("NOTICE_TO_POLICYHOLDERS", _);

        function DocumentType(value:String = null, restrictor:* = null) {
            super((value || QUOTE_SCHEDULE.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [QUOTE_SCHEDULE, DEBIT_NOTE, KEY_FACTS, POLICY_SUMMARY, IPID, WORDINGS, POLICY_SCHEDULE, STORAGE_QUESTIONNAIRE, CLAUSE, RATING_SCHEDULE, SCHEDULE, CANCELLATION_NOTE, DEFINITIONS, POLICY_CHANGES, NOTICE_TO_POLICYHOLDERS];
        }

        public static function valueOf(name:String):DocumentType {
            return DocumentType(QUOTE_SCHEDULE.constantOf(name));
        }
    }
}