/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.documents.document {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.documents.document.DocumentHeaderFooterLine$LineType")]
    public class DocumentHeaderFooterLine$LineType extends Enum {

        public static const HEADER:DocumentHeaderFooterLine$LineType = new DocumentHeaderFooterLine$LineType("HEADER", _);
        public static const FOOTER:DocumentHeaderFooterLine$LineType = new DocumentHeaderFooterLine$LineType("FOOTER", _);

        function DocumentHeaderFooterLine$LineType(value:String = null, restrictor:* = null) {
            super((value || HEADER.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [HEADER, FOOTER];
        }

        public static function valueOf(name:String):DocumentHeaderFooterLine$LineType {
            return DocumentHeaderFooterLine$LineType(HEADER.constantOf(name));
        }
    }
}