/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.sourceassociation {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.sourceassociation.Channel")]
    public class Channel extends Enum {

        public static const WEB:Channel = new Channel("WEB", _);
        public static const WS:Channel = new Channel("WS", _);

        function Channel(value:String = null, restrictor:* = null) {
            super((value || WEB.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [WEB, WS];
        }

        public static function valueOf(name:String):Channel {
            return Channel(WEB.constantOf(name));
        }
    }
}