/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.reference.deductible
{
	import com.catlin.cargo.model.core.covertype.CoverTypeCode;

	import mx.collections.ArrayCollection;

	[Bindable]
	[RemoteClass(alias="com.catlin.cargo.model.reference.deductible.Deductible")]
	public class Deductible extends DeductibleBase {

		public static const DEDUCTIBLE_COVER_TYPE_GROUP_GLOBAL:String="GLOBAL";

		public static function getDeductiblesForCoverTypeGroup(deductiblesMap:Object, coverType:CoverTypeCode):ArrayCollection {

			if (!deductiblesMap)
				return null;

			var ret:Object=deductiblesMap[coverType.name] != null ? 
				deductiblesMap[coverType.name] : 
				deductiblesMap[Deductible.DEDUCTIBLE_COVER_TYPE_GROUP_GLOBAL];

			return ret != null ? ret as ArrayCollection : new ArrayCollection();
		}
	}
}