/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.risk {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.CommissionType")]
    public class CommissionType extends Enum {

        public static const GROSS:CommissionType = new CommissionType("GROSS", _);
        public static const NET:CommissionType = new CommissionType("NET", _);

        function CommissionType(value:String = null, restrictor:* = null) {
            super((value || GROSS.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [GROSS, NET];
        }

        public static function valueOf(name:String):CommissionType {
            return CommissionType(GROSS.constantOf(name));
        }
    }
}