/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.risk {

    public interface CoverElement {

        function set calculatedPremium(value:Number):void;
        function get calculatedPremium():Number;

        function set calculatedRate(value:Number):void;
        function get calculatedRate():Number;

        function get limit():Number;

        function get rate():Rate;
    }
}