/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.risk {
	
	import mx.collections.ArrayCollection;
	
    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.ExhibitionCover")]
    public class ExhibitionCover extends ExhibitionCoverBase {
		
		public function ExhibitionCover() {
			
    		excessof30Days = false;
			basisOfValuation = "Current Market Value";

			details = new ArrayCollection();
			
			var ukDetail:ExhibitionCoverDetail = new ExhibitionCoverDetail();
			ukDetail.territory = ExhibitionCover$ExhibitionCoverTerritory.DOMESTIC;
			details.addItem(ukDetail);
			
			var rowDetail:ExhibitionCoverDetail = new ExhibitionCoverDetail();
			rowDetail.territory = ExhibitionCover$ExhibitionCoverTerritory.ROW;
			details.addItem(rowDetail);
			
			details[0].limit;
			
		}
		
		public function getDetailFor(territory:ExhibitionCover$ExhibitionCoverTerritory):ExhibitionCoverDetail {
			for each (var exhibitionCoverDetail:ExhibitionCoverDetail in details) {
				if (exhibitionCoverDetail.territory == territory) {
					return exhibitionCoverDetail;
				}
			}
			return null;
		}
		
    }
    
}
