/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.risk {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.ExhibitionCover$ExhibitionCoverTerritory")]
    public class ExhibitionCover$ExhibitionCoverTerritory extends Enum {

        public static const DOMESTIC:ExhibitionCover$ExhibitionCoverTerritory = new ExhibitionCover$ExhibitionCoverTerritory("DOMESTIC", _);
        public static const ROW:ExhibitionCover$ExhibitionCoverTerritory = new ExhibitionCover$ExhibitionCoverTerritory("ROW", _);

        function ExhibitionCover$ExhibitionCoverTerritory(value:String = null, restrictor:* = null) {
            super((value || DOMESTIC.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [DOMESTIC, ROW];
        }

        public static function valueOf(name:String):ExhibitionCover$ExhibitionCoverTerritory {
            return ExhibitionCover$ExhibitionCoverTerritory(DOMESTIC.constantOf(name));
        }
    }
}