/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.risk {
	import com.catlin.cargo.model.util.PersistentDateFormat;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.MidTermAdjustmentDetails")]
    public class MidTermAdjustmentDetails extends MidTermAdjustmentDetailsBase {
		
		private var dateFormat:PersistentDateFormat = new PersistentDateFormat();
		
		public function get endorsementStartDateAsDate():Date {
			return dateFormat.parse(endorsementStartDate);
		}
		
		public function set endorsementStartDateAsDate(date:Date):void {
			endorsementStartDate = dateFormat.format(date);
		}
		
    }
}