/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.risk {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.PolicyType")]
    public class PolicyType extends Enum {

        public static const ANNUAL:PolicyType = new PolicyType("ANNUAL", _);
        public static const SINGLE:PolicyType = new PolicyType("SINGLE", _);

        function PolicyType(value:String = null, restrictor:* = null) {
            super((value || ANNUAL.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [ANNUAL, SINGLE];
        }

        public static function valueOf(name:String):PolicyType {
            return PolicyType(ANNUAL.constantOf(name));
        }
    }
}