/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.risk {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.PremiumType")]
    public class PremiumType extends Enum {

        public static const FNA:PremiumType = new PremiumType("FNA", _);
        public static const MAD:PremiumType = new PremiumType("MAD", _);
        public static const BOTH:PremiumType = new PremiumType("BOTH", _);

        function PremiumType(value:String = null, restrictor:* = null) {
            super((value || FNA.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [FNA, MAD, BOTH];
        }

        public static function valueOf(name:String):PremiumType {
            return PremiumType(FNA.constantOf(name));
        }
    }
}