/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.risk {

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.Rate")]
    public class Rate extends RateBase {
		public function Rate() {
			premium = 0;
			tax = 0;
		}
    }
}