/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.risk {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.RiskStatus")]
    public class RiskStatus extends Enum {

        public static const NEW:RiskStatus = new RiskStatus("NEW", _);
        public static const QUOTED:RiskStatus = new RiskStatus("QUOTED", _);
        public static const QUOTE_EXPIRED:RiskStatus = new RiskStatus("QUOTE_EXPIRED", _);
        public static const REFERRED:RiskStatus = new RiskStatus("REFERRED", _);
        public static const QUOTE_PENDING:RiskStatus = new RiskStatus("QUOTE_PENDING", _);
        public static const OFFLINE:RiskStatus = new RiskStatus("OFFLINE", _);
        public static const POLICY:RiskStatus = new RiskStatus("POLICY", _);
        public static const DECLINED:RiskStatus = new RiskStatus("DECLINED", _);
        public static const EXPIRED:RiskStatus = new RiskStatus("EXPIRED", _);
        public static const NTU:RiskStatus = new RiskStatus("NTU", _);
        public static const CANCELLED:RiskStatus = new RiskStatus("CANCELLED", _);
        public static const LAPSED:RiskStatus = new RiskStatus("LAPSED", _);

        function RiskStatus(value:String = null, restrictor:* = null) {
            super((value || NEW.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [NEW, QUOTED, QUOTE_EXPIRED, REFERRED, QUOTE_PENDING, OFFLINE, POLICY, DECLINED, EXPIRED, NTU, CANCELLED, LAPSED];
        }

        public static function valueOf(name:String):RiskStatus {
            return RiskStatus(NEW.constantOf(name));
        }
    }
}