/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.risk {
	import com.catlin.cargo.model.core.originatingoffice.OriginatingOfficeCode;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.RiskReportSearchCriteria")]
    public class RiskReportSearchCriteria extends RiskReportSearchCriteriaBase {
		
		private static const _importedClasses:Array=[OriginatingOfficeCode, RiskStatus];
		
    }
}