/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.risk {

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.RiskClause")]
    public class RiskClause extends RiskClauseBase {

		private var _tempUid:String = null;
		
        override public function set uid(value:String):void {
            super.uid = value;
        }
        override public function get uid():String {
            if (isNaN(sid)) {
                if (_tempUid == null) {
                	_tempUid = UIDUtil.createUID();
                }
                return _tempUid;
            }
            return super.uid;
        }
    }
}