/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.risk {

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.RiskSearchResult")]
    public class RiskSearchResult extends RiskSearchResultBase {
		// ***** String date functions
		public function get policyStartDateAsDate():Date {
			return toDate(policyStartDate);
		} 
		
		private function toDate(dt:String):Date {
			if (dt == null || dt.length != 8) {
				return null;
			}
			var date:Date = new Date();
			date.fullYear = Number(dt.substr(0, 4));
			date.month = Number(dt.substr(4, 2)) - 1;
			date.date = Number(dt.substr(6, 2));
			return date;
		}		
    }
}