/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.risk {
	import mx.controls.Alert;
	

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.StockLocation")]
    public class StockLocation extends StockLocationBase {
    	
		public function StockLocation() {
			limit = 0;
			alarmed = false;
			standardConstruction = false;
		}
		
    	public function get addressAsSingleLine():String {
    		var result:String = "";
    		if (address != null) { 
				if (address.addressLine1 != null) result += address.addressLine1;
	    		result += append(address.addressLine2);
	    		result += append(address.addressLine3);
	    		result += append(address.townCity);
	    		result += append(address.postcode);
			}
			return result;    		
    	}
    	
    	private function append(s:String):String {
    		if (s == null || s.length == 0) return "";
    		return ", " + s;
    	}
    }
}