/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.risk {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.TaxCode")]
    public class TaxCode extends Enum {

        public static const IPT:TaxCode = new TaxCode("IPT", _);
        public static const GST:TaxCode = new TaxCode("GST", _);
        public static const ASD:TaxCode = new TaxCode("ASD", _);
        public static const ISD:TaxCode = new TaxCode("ISD", _);

        function TaxCode(value:String = null, restrictor:* = null) {
            super((value || IPT.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [IPT, GST, ASD, ISD];
        }

        public static function valueOf(name:String):TaxCode {
            return TaxCode(IPT.constantOf(name));
        }
    }
}