/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.risk {

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.ToolsAndSamplesCover")]
    public class ToolsAndSamplesCover extends ToolsAndSamplesCoverBase {
		public function ToolsAndSamplesCover() {
			numberOfVehicles = 0;
			vehicleLimit = 0;
			basisOfValuation = "Current Market Value";
		}
    }
}