/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.core.risk {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.TriaInsuranceStatus")]
    public class TriaInsuranceStatus extends Enum {

        public static const NOT_OFFERED:TriaInsuranceStatus = new TriaInsuranceStatus("NOT_OFFERED", _);
        public static const ACCEPTED:TriaInsuranceStatus = new TriaInsuranceStatus("ACCEPTED", _);
        public static const REJECTED:TriaInsuranceStatus = new TriaInsuranceStatus("REJECTED", _);
        public static const NOT_REQUIRED:TriaInsuranceStatus = new TriaInsuranceStatus("NOT_REQUIRED", _);

        function TriaInsuranceStatus(value:String = null, restrictor:* = null) {
            super((value || NOT_OFFERED.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [NOT_OFFERED, ACCEPTED, REJECTED, NOT_REQUIRED];
        }

        public static function valueOf(name:String):TriaInsuranceStatus {
            return TriaInsuranceStatus(NOT_OFFERED.constantOf(name));
        }
    }
}