/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.reference.exchangerate {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.reference.exchangerate.ExchangeRateType")]
    public class ExchangeRateType extends Enum {

        public static const CCY_FX_RATE_MONTHLY:ExchangeRateType = new ExchangeRateType("CCY_FX_RATE_MONTHLY", _);

        function ExchangeRateType(value:String = null, restrictor:* = null) {
            super((value || CCY_FX_RATE_MONTHLY.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [CCY_FX_RATE_MONTHLY];
        }

        public static function valueOf(name:String):ExchangeRateType {
            return ExchangeRateType(CCY_FX_RATE_MONTHLY.constantOf(name));
        }
    }
}