/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.geo.location {

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.geo.location.Location")]
    public class Location extends LocationBase {
		public static const DOMESTIC_CODE:String = "DOMESTIC";
    }
}