/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.brokercontact {

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.brokercontact.BrokerContact")]
    public class BrokerContact extends BrokerContactBase {
    	
    	public function BrokerContact() {
    		enabled = true;
    	}
    }
}