/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core {
	import com.catlin.model.EmbeddedAuditInformation;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.SIDModelBase")]
    public class SIDModelBase extends SIDModelBaseBase {
		public function SIDModelBase() {
			auditInformation = new EmbeddedAuditInformation();
		}
    }
}