/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.risk.report {
	import flash.utils.IDataInput;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.risk.report.RiskReportGrossPerMonthChartItem")]
    public class RiskReportGrossPerMonthChartItem extends RiskReportGrossPerMonthChartItemBase {
		
		
		private var _period:Date;
		private var _periodStr:String;

		public function get period():Date {
			return _period;
		}

		public function get periodStr():String {
			return _periodStr;
		}
		
		override public function readExternal(input:IDataInput):void {
			super.readExternal(input);
			_period = new Date(year, month);
			_periodStr = month + "/" + year;
		}	
	
    }
}