/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.security {
	import com.catlin.cargo.model.core.originatingoffice.OriginatingOfficeCode;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.security.UserInfo")]
    public class UserInfo extends UserInfoBase {
    	
		public var isBroker:Boolean = false;
		public var isUnderwriter:Boolean = false;
		public var isSupport:Boolean = false;
		
    	public function initialiseRoles():void {
			for each (var authority:String in authorities) {
				switch (authority) {
					case "ROLE_BROKER": isBroker = true; break;
					case "ROLE_UNDERWRITER": isUnderwriter = true; break;
					case "ROLE_SUPPORT": isSupport = true; break;
				}
			}
    	}
		
		public function isAsianOriginatingOffice():Boolean {
			if (originatingOffice.code == OriginatingOfficeCode.HK || originatingOffice.code == OriginatingOfficeCode.SG) {
				return true;
			} else {
				return false;
			}
		}  
    }
}