/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.reference.financialregulation {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.reference.financialregulation.FinancialControlRegulationType")]
    public class FinancialControlRegulationType extends Enum {

        public static const CONSUMER_BUSINESS_CONTROL:FinancialControlRegulationType = new FinancialControlRegulationType("CONSUMER_BUSINESS_CONTROL", _);

        function FinancialControlRegulationType(value:String = null, restrictor:* = null) {
            super((value || CONSUMER_BUSINESS_CONTROL.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [CONSUMER_BUSINESS_CONTROL];
        }

        public static function valueOf(name:String):FinancialControlRegulationType {
            return FinancialControlRegulationType(CONSUMER_BUSINESS_CONTROL.constantOf(name));
        }
    }
}