/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.core.underwriter {

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.core.underwriter.Underwriter")]
    public class Underwriter extends UnderwriterBase {
    	
    	public function Underwriter() {
    		enabled = true;
    	}
    }
}