/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERWRITTEN EACH TIME YOU USE
 * THE GENERATOR.
 */

package com.catlin.cargo.model.reference.country {

    import org.granite.util.Enum;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.reference.country.IsoCountryCode")]
    public class IsoCountryCode extends Enum {

        public static const AU:IsoCountryCode = new IsoCountryCode("AU", _);
        public static const GB:IsoCountryCode = new IsoCountryCode("GB", _);
        public static const HK:IsoCountryCode = new IsoCountryCode("HK", _);
        public static const IE:IsoCountryCode = new IsoCountryCode("IE", _);
        public static const MT:IsoCountryCode = new IsoCountryCode("MT", _);
        public static const SG:IsoCountryCode = new IsoCountryCode("SG", _);
        public static const US:IsoCountryCode = new IsoCountryCode("US", _);

        function IsoCountryCode(value:String = null, restrictor:* = null) {
            super((value || AU.name), restrictor);
        }

        override protected function getConstants():Array {
            return constants;
        }

        public static function get constants():Array {
            return [AU, GB, HK, IE, MT, SG, US];
        }

        public static function valueOf(name:String):IsoCountryCode {
            return IsoCountryCode(AU.constantOf(name));
        }
    }
}