/**
 * Generated by Gas3 v2.2.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.catlin.cargo.model.reference.country {
	import mx.collections.ArrayCollection;

    [Bindable]
    [RemoteClass(alias="com.catlin.cargo.model.reference.country.Region")]
    public class Region extends RegionBase {

		public function getCountries():ArrayCollection {
			var countries:ArrayCollection = new ArrayCollection();
			if (this.territories != null && this.territories.length > 0) {
				for each (var item:Territory in this.territories) {
					if (item is Country)
						countries.addItem(item);
				}
			}	
			return countries;
		}

		public function getTerritories():ArrayCollection {
			var territories:ArrayCollection = new ArrayCollection();
			if (this.territories != null && this.territories.length > 0) {
				territories.addAll(this.territories);
			}	
			return territories;
		}		
		
		public function getProvinces():ArrayCollection {
			var provinces:ArrayCollection = new ArrayCollection();
			for each (var item:Territory in this.territories) {
				if (item is Province)
					provinces.addItem(item);
			}
			return provinces;
		}
    }
}